### ISSUE TITLE
pyqtgraph error - levels argument required

### ISSUE THREAD

**Issue by postpop** [janclemenslab/das#11]
I downloaded the new version from the GitHub page and unfortunately, there seems to be a new error - now whenever I load any audio file, this pops up
<img width="565" alt="Screen Shot 2021-07-09 at 12 01 27 PM" src="https://user-images.githubusercontent.com/43159725/125106290-7b728980-e0ad-11eb-88e5-122b3d043bf9.png">

_Originally posted by @emorysaba in https://github.com/janclemenslab/das/issues/10#issuecomment-877290669_

**Comment by postpop** [comment]
Hi @emorysaba,

the issue is caused by yesterday's pyqtgraph release (v0.12.2). I will pin the version in the package for now to fix this.

A quick fix for you, beyond reinstalling _das_, would be to downgrade pyqtgraph to v0.12.1 with `pip install pyqtgraph==0.12.1`. That solved it for me...

**Comment by emorysaba** [comment]
Hi! This seems to fix this issue - thank you!
