### ISSUE TITLE
Error opening wav file

### ISSUE THREAD

**Issue by emorysaba** [janclemenslab/das#12]
Hello again! Unfortunately I've run into another issue - when I try to open some wav files, I get the following error. Any help debugging what could be going wrong here (including there being potential issues with my wav file) would be much appreciated!
<img width="897" alt="Screen Shot 2021-09-04 at 3 33 49 PM" src="https://user-images.githubusercontent.com/43159725/132106023-225588f6-3a17-49e9-98fa-9c8beadb7c93.png">

**Comment by postpop** [comment]
Hi, this looks as if the wav file is too short (only 6000 samples). Is that possible? Best to try and load the wav file with [scipy.io.wavfile.read](https://docs.scipy.org/doc/scipy/reference/generated/scipy.io.wavfile.read.html#scipy.io.wavfile.read) to check that everything is okay with the file.

**Comment by emorysaba** [comment]
Yep, I determined that that was the issue - thank you!!
