### ISSUE TITLE
current das cannot load newly generated idswaps.txt

### ISSUE THREAD

**Issue by stein-e** [janclemenslab/das#19]
das gui saves fly idswaps in time format (float) but can only load frames (integers). upgrading xarray-behave in the das environment fixes the error.

das comes with xarray-behave version 0.28.2. the current xarray-behave version (0.29.6) has no problems loading idswaps in time format.

**Comment by postpop** [comment]
A fresh DAS install should come with xarray-behave 0.29.x, not 0.28.2. Just checked the tests again. Probably sth else wrong. Let's have a look on Monday.
