### ISSUE TITLE
issue installing das

### ISSUE THREAD

**Issue by emorysaba** [janclemenslab/das#23]
Hello! I am trying to install DAS on my local computer but unfortunately, I have not been able to do so because the installation has gotten stuck on the solving environment step for a long amount of time (>16 hours). I have previously downloaded DAS and have not had this issue before, are there any steps I can take to eliminate this problem?

**Comment by postpop** [comment]
Hi! I'll look into this - maybe there is an issue with the install package. Which operating system are you using?

As a quick fix, you could use [mamba](https://github.com/mamba-org/mamba), which is replacement of conda that is much faster.

Install mamba into your base environment:
`conda install mamba -n base -c conda-forge`

This won't change how conda itself works - it just adds the `mamba` command as a potential replacement.

Then install DAS by replacing `conda` with `mamba` in the command:
`mamba create python=3.8 das -c conda-forge -c ncb -n das` 

This should be much faster (<2 minutes on my mac).

**Comment by emorysaba** [comment]
Looks like my base environment had gotten too large - created a new one, installed mamba there, and then created the DAS environment and that worked well. Thank you!
