### ISSUE TITLE
Predict in GUI not working

### ISSUE THREAD

**Issue by emorysaba** [janclemenslab/das#24]
Hello again! I apologize for posting so much here, but in trying to use the predict function in the GUI today I was presented with this error when I selected a model to use:

```
Traceback (most recent call last):
  File "/Applications/anaconda3/envs/base2/envs/das/lib/python3.8/site-packages/xarray_behave/gui/app.py", line 1677, in <lambda>
    menuitem.triggered.connect(lambda: callback(qt_keycode))
  File "/Applications/anaconda3/envs/base2/envs/das/lib/python3.8/site-packages/xarray_behave/gui/app.py", line 611, in das_predict
    dialog.form['segment_fillgap'] = params['post_opt']['gap_dur']
TypeError: 'bool' object is not subscriptable
```

Any help with how to fix this would be much appreciated!

**Comment by postpop** [comment]
Hi, thanks for spotting this bug. It will take a day or so until the fix is reflected in the conda package but you can update the fixed dependency in your current DAS env: `pip install xarray-behave --no-deps --upgrade`.

**Comment by emorysaba** [comment]
I ran this update but unfortunately, the issue is still persisting!

**Comment by postpop** [comment]
Could you try updating in the DAS env again: `pip install xarray-behave --no-deps --upgrade`. Should work now.

**Comment by emorysaba** [comment]
Working now, thank you!
