### ISSUE TITLE
speeding up das.predict.predict

### ISSUE THREAD

**Issue by emorysaba** [janclemenslab/das#25]
Hello! I was wondering if there were any way to speed up the predict function when using the python module - I am currently annotating several hundred wav files each 10 minutes long, and it takes my local computer ~3 minutes/file, which is slow. Are there any steps I can take to speed up this process in the notebook? Thank you for all the help!

**Comment by postpop** [comment]
Hi! We recently enabled eager execution, which may slow things down a bit. You could enable eager execution again and see if this speeds things up. In your notebook right after importing tensorflow, just add these two lines:
```python
from tensorflow.python.framework.ops import disable_eager_execution
disable_eager_execution()
```
Eager to hear whether this helps as I have not test this at all...

**Comment by emorysaba** [comment]
Unfortunately doing so raises the following error:
`ValueError: Calling `Model.predict` in graph mode is not supported when the `Model` instance was constructed with eager mode enabled. Please construct your `Model` instance in graph mode or call `Model.predict` with eager mode enabled.`

**Comment by postpop** [comment]
I see - I guess you'd have to train with eager mode disabled but I'm not sure this would speed things up. What's the sample rate of you files and what network parameters do you use? If speed is an issue, maybe you could simplify the model.
