### ISSUE TITLE
DAS predict clean up fails if only used for events

### ISSUE THREAD

**Issue by MaximilianHoffmann** [janclemenslab/das#32]
``` 
 File "anaconda3\envs\das\lib\site-packages\xarray_behave\gui\app.py", line 1669, in <lambda>
    menuitem.triggered.connect(lambda: callback(qt_keycode))
  File "anaconda3\envs\das\lib\site-packages\xarray_behave\gui\app.py", line 729, in das_predict
    detected_segment_names = [segments['names'][ii] for ii in detected_segment_names]
  File "anaconda3\envs\das\lib\site-packages\xarray_behave\gui\app.py", line 729, in <listcomp>
    detected_segment_names = [segments['names'][ii] for ii in detected_segment_names]
TypeError: list indices must be integers or slices, not NoneType
```
at least it looks like it is searching for segments, but I only defined events.

**Comment by postpop** [comment]
Mmh, we often run DAS with events only. Can you share the model and params file, as well as the recording that triggered the error? Thanks!

**Comment by MaximilianHoffmann** [comment]
Sure! 


it's here: https://owncloud-ext.charite.de/owncloud/index.php/s/RYoxKLiC51W3FmR  Thank you for looking it to it.

**Comment by postpop** [comment]
Fixed the problem - was an unexpected edge case. Thanks again for helping make DAS more robust!
Apply the fix by updating the gui with `pip install xarray-behave --upgrade --no-deps`.
Will take a bit longer until this is live on conda/mambe.

**Comment by MaximilianHoffmann** [comment]
Hi, thanks for looking iinto this. The predicitons doesn't crash right now, however I don't see any proposals. 

```
     149/149 [==============================] - 207s 1s/step
  INFO:root:   found 1221 instances of events '['click']'.
  Traceback (most recent call last):
    File "C:\Users\jlab\anaconda3\envs\das\lib\site-packages\xarray_behave\gui\app.py", line 1669, in <lambda>
      menuitem.triggered.connect(lambda: callback(qt_keycode))
    File "C:\Users\jlab\anaconda3\envs\das\lib\site-packages\xarray_behave\gui\app.py", line 729, in das_predict
      detected_segment_names = [segments['names'][ii] for ii in detected_segment_names]
    File "C:\Users\jlab\anaconda3\envs\das\lib\site-packages\xarray_behave\gui\app.py", line 729, in <listcomp>
      detected_segment_names = [segments['names'][ii] for ii in detected_segment_names]
  TypeError: list indices must be integers or slices, not NoneType
```

The predict call ends with this Error/Warning. Am I missing something?

**Comment by postpop** [comment]
Hi, which version are you on? I think this was fixed in the latest version - you can update DAS (no the GUI this time) via
`pip install das --upgrade --no-deps`. Let me know if that solves it or if the error persists...

**Comment by MaximilianHoffmann** [comment]
Thanks, I was still at 0.26.4, works now, thank you.
