### ISSUE TITLE
DAS gui freezes if threshold smoothing factor is set to 0

### ISSUE THREAD

**Issue by avakiai** [janclemenslab/das#34]
Hi there!
I'm using DAS to detect some bat calls in my audio files. Installation and initial use works well, but as I'm trying to annotate my files using the thresholding mode, I'm running into an issue that I'm not quite sure how to solve. 

My workflow is to (1) add a new type of song, in this case "echo"; (2) manually set the threshold; then (3) generate detections (shortcut "i"). This works well but I find that if I then adjust the threshold manually and try to generate detections again (for example because calls were not detected in a given section), DAS starts throwing errors and stops properly responding to commands. 

More specifically:
* any attempt to change the view of the spectogram/oscillogram via the keyboard commands A/D/W/S or the scrollbar results in the following error in the terminal, while the spectrogram doesn't systematically change: 
```
Traceback (most recent call last):
  File "C:\Users\AC-Lab-AKK\anaconda3\envs\das\lib\site-packages\xarray_behave\gui\app.py", line 1533, in <lambda>
    self.scrollbar.valueChanged.connect(lambda value: setattr(self, 't0', value))
  File "C:\Users\AC-Lab-AKK\anaconda3\envs\das\lib\site-packages\xarray_behave\gui\app.py", line 1602, in t0
    self.update_xy()
  File "C:\Users\AC-Lab-AKK\anaconda3\envs\das\lib\site-packages\xarray_behave\gui\app.py", line 1939, in update_xy
    self.envelope = self.get_envelope()
  File "C:\Users\AC-Lab-AKK\anaconda3\envs\das\lib\site-packages\xarray_behave\gui\app.py", line 1754, in get_envelope
    env = np.sqrt(np.convolve(self.y.astype(np.float)**2, win, mode='same'))
  File "<__array_function__ internals>", line 180, in convolve
  File "C:\Users\AC-Lab-AKK\anaconda3\envs\das\lib\site-packages\numpy\core\numeric.py", line 843, in convolve
    raise ValueError('v cannot be empty')
ValueError: v cannot be empty
```

* Another oddity is that the scrollbar develops erratic behavior. Clicking on a region on the scrollbar usually does nothing, but sometimes does. Pulling it quickly in one direction or another does get the spectrogram to shift, but the display and the scrollbar are uncalibrated, e.g. when the scrollbar should be at timepoint zero, the spectro shows some other time value at point 0. You can see this [in this screencast](https://drive.google.com/file/d/1EkikccOQaS2l46CpBJBG8GhzqwVK61G_/view?usp=sharing).

* Meanwhile, mouse-clicking on the spectrogram to add an annotation results in a normal-looking terminal message, like so: 
```
INFO:root:  Added echo at t=[0.9677:0.9677] seconds.
```
but no event appears on the spectrogram. 

[Here too is a screencast](https://drive.google.com/file/d/1T44_B9gYWVdQA2315KiuEFcUrjGbroPF/view?usp=sharing) showing the workflow leading up to an including the error. It occurs at about 2:20 minutes. 

For reference, my machine is running Windows 10, and my conda version is 4.12. 
I initially ran into this problem annotating long files (7.5 minutes long), so I cut a 30-second segment and used that but the problem still occurred. (Errors above reported from 30-second .wav file.) 

Not sure if this may play a role, but when initializing das gui, I get the following warning on my terminal (even after installing Visual C++):
```
warning:root:no tensorflow-probability
```

Finally, I should mention that I'm actually running all of this not on my local machine but on a lab computer controlled through Google's Remote Desktop via Chrome. However, I don't suppose this should have an influence, as I have full control of the computer from remote. 

I'd be grateful for any advice! Thanks!

----
EDIT:  In fact, without doing anything the gui became responsive again. Now I'm finding that as I go through my file to annotate every few seconds, I sometimes end up in that non-responsive loop again, and some clicking around eventually "releases" it and I can continue. Not sure how to systematically describe now under what conditions it freezes/unfreezes...

---- 
EDIT 2 - 3: I discovered that if the smoothing factor under `Adjust thresholding mode` is set to zero, the un-responsiveness is triggered until it is changed back to a value greater than zero! I **~~don't~~** think this accounts for **[pretty much]** all the occasions on which some freezing occurred ~~, but I think a significant amount is explained by this~~ !

**Comment by postpop** [comment]
Hi Ava,

thanks for reporting all these issues! We had recently fixed some bugs with the scrollbar when files were long. Maybe re-installing to the latest version solves some of the problems. Can you send the output of `das version`? The latest version of the GUI `xarray-behave` is 0.33.0. I'll look into the other issues in the next couple of days.

**Comment by avakiai** [comment]
Hi Jan and team, 

Thanks for the quick reply! Indeed it looks like I'm running a previous version of the GUI, even though I installed only a few days ago. Here's my das version: 

```
(das) C:\Users\AC-Lab-AKK>das version
WARNING:root:No tensorflow-probability.
INFO:das.cli:  Windows-10-10.0.19041-SP0
INFO:das.cli:  DAS v0.26.4
INFO:das.cli:     GUI is available.
INFO:das.cli:     xarray-behave v0.32.8
INFO:das.cli:     pyqtgraph v0.12.4
INFO:das.cli:     PySide2 v5.13.2
INFO:das.cli:     Qt v5.12.9
INFO:das.cli:
INFO:das.cli:  tensorflow v2.6.0
INFO:das.cli:  keras v2.6.0
INFO:das.cli:     GPU is  available.
INFO:das.cli:
INFO:das.cli:  python v3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:50:36) [MSC v.1929 64 bit (AMD64)]
INFO:das.cli:  pandas v1.4.2
INFO:das.cli:  numpy v1.22.4
INFO:das.cli:  h5py v3.6.0
INFO:das.cli:  scipy v1.8.1
INFO:das.cli:  scikit-learn v1.1.1
INFO:das.cli:  xarray v2022.3.0
```
Is there a way of just updating the gui and not the whole das? Or would you recommend doing a full install? 

Incidentally, I have not had any other issues with the gui and annotations is now very smooth - I wonder if I was just overloading the gui by moving too fast/not interacting with it as it expects?

Thanks!

**Comment by postpop** [comment]
Hi Ava,

you can update the GUI via `pip install xarray-behave --upgrade --no-deps`. This may break things - if so, just re-install from scratch.

We also noticed that the GUI becomes less responsive the longer the program is active but couldn't find a reason - we'll look into this further. I'll also push a fix that ensure that the smoothing factor is always >0.

**Comment by avakiai** [comment]
Hi Jan & team, 

I'm closing this issue/editing the title because I'm fairly certain the bugginess was caused simply by the smoothing factor being set to 0. 

The gui otherwise works fine - I also just updated xarray. 

Thanks!
