### ISSUE TITLE
[feature request] undo/redo & annotation duration indicator

### ISSUE THREAD

**Issue by avakiai** [janclemenslab/das#35]
Dear Jan & team, 
I wanted to mention two features I thought would be very useful for the DAS gui. (My sincere apologies if these are somehow already implemented and I may have missed them!):

1. **undo/redo feature**: The existing keyboard shortcuts are extremely useful and well thought-out. I did however find myself often wishing there was a way to undo or redo a change I made to an annotation, especially when trying to remove annotations (Y), re-threshold and re-detect events (I) in a section of the spectrogram.

2. **annotation duration display**: In my particular case (and perhaps for many others), the duration of audio events is very diagnostic as to whether an event belongs in one class or another. However, as the events I work with (bat echolocation calls vs. communication calls) are very short in duration, it can be somewhat challenging to see how long the current annotation is. A small display in one corner that may indicate live (i.e. as you are creating/editing an annotation, or for a selected annotation) the duration in seconds would be extremely useful!

If I get some time in the next few weeks, I may try to play around with the code to see if I can implement a rough version myself and open a pull request. 

Thanks!

**Comment by postpop** [comment]
Thank you for the suggestions - it's great to get feedback from our users! Displaying the duration while creating/editing an annotation should be fairly straightforward to implement. I assume a way to change the class of existing annotations would be useful in that case as well, right? Maybe this could be exposed by hovering with the mouse over an annotation and pressing the number key associated with the new class. An undo/redo feature would also be useful. Implementing this will require structural changes to the GUI since we'll have to start keeping tracking of all changes to the program.

**Comment by avakiai** [comment]
Hi there, 

Indeed, I think being able to change the class of existing annotation would be a great feature!

I had collected some more feature requests I thought I'd add to the above:
* **Error message if user attempts to annotate before having added a song type**: at the beginning I recall not understanding why I couldn't make annotations, then realized I had forgotten to add a class type first. Even now I sometimes open a file and start clicking around, forgetting I need to do that first. An error message could remind the user to do this if click events are logged before a class is named. Alternatively, perhaps annotations would be accepted under a default, genertic type name that the user could change later?
* **Accept a .config file for thresholding, annotation**; or retain memory of parameters when a new file is opened in the session in the gui: when one opens a new file in the gui, any previously modified Annotation parameters revert back to the default (e.g. Only edit active song type) and have to be changed again, if desired. This can make it a bit cumbersome if the user needs to annotate many files at once and doesn't want to use the default settings. Would it be possible either to retain user-modified settings until the gui is closed, and/or allow the user to upload a .config file at the start of the session?
* **Retain directory and filename information in save as dataset**: when users annotate a file using the GUI, then go to Export for DAS to save the file as an .npz, a navigation window opens for the user to select where to save the file. For me, this window always opens in my machine's local root directory, e.g. `C:/Users/Ava Kiai/`, and the field for the filename is blank. I can't recall exactly where, but I don't think this was the behavior for other commands that open navigation windows - in other places in DAS, it seemed to open the working directory by default or perhaps the last visited directory. I think either of these would be more useful than opening in the local base, which requires lots of clicking to get back to the working directory. The filename also could be inherited from the open file in the DAS gui, which would save the user from entering it in again.

**Comment by postpop** [comment]
Hi Ava, thanks for these suggestions.
Two improvements are currently implemented on the version on github:
- You can change the class of an annotation by Ctrl or Cmd clicking on an existing annotation. The class of the clicked annotation will change to the currently selected on.
- An error message will now pop-up when you try to annotate w/o having created song types. The message will allow you to directly open the dialog for creating song types.

We will integrate them into the conda packages soon - you can try them by pip-upgrading xarray-behave (the GUI): `pip install xarray-behave --upgrade --no-deps --force`.

As for the other suggestions: I aggree that a .config file with defaults would be really useful and should be doable, and the directories/filenames in some of the save/export dialogs are currently a mess. We'll look into implementing/fixing this.

**Comment by avakiai** [comment]
Hi Jan, 
Wow, really cool to see these updates coming in so fast. :) Thanks! I'll give the new update a go.
