### ISSUE TITLE
Annotations do not load unless file ends in "annotations.csv"

### ISSUE THREAD

**Issue by avakiai** [janclemenslab/das#38]
Hi Jan, 

When loading .wav files into the das gui for annotating/updating annotations, it seems that the gui does not load them unless the annotations file ends in "annotations.csv" (the default). This can cause issues if one needs to create different sets of annotations for different purposes for the same .wav file. 

| Edit: Perhaps this behavior is intended, in which case this is more of a feature request that annotation files be read regardless of filename. 

Note that, while it's possible to select the correct .csv file from the load data pop-up, no annotations appear unless the file has the default filename ending. 

For reference, my system/install is:
```
INFO:das.cli:  Windows-10-10.0.22000-SP0
INFO:das.cli:  DAS v0.26.6
INFO:das.cli:     GUI is available.
INFO:das.cli:     xarray-behave v0.33.0
INFO:das.cli:     pyqtgraph v0.12.4
INFO:das.cli:     PySide2 v5.13.2
INFO:das.cli:     Qt v5.12.9
INFO:das.cli:
INFO:das.cli:  tensorflow v2.6.0
INFO:das.cli:  keras v2.6.0
INFO:das.cli:     GPU is  available.
INFO:das.cli:
INFO:das.cli:  python v3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:50:36) [MSC v.1929 64 bit (AMD64)]
INFO:das.cli:  pandas v1.4.3
INFO:das.cli:  numpy v1.23.1
INFO:das.cli:  h5py v3.7.0
INFO:das.cli:  scipy v1.8.1
INFO:das.cli:  scikit-learn v1.1.1
INFO:das.cli:  xarray v2022.3.0
``` 

- ava

**Comment by postpop** [comment]
Ha, yes, that has bugged us as well but never enough to fix it. 
I've pushed a fix to the gui with v0.33.1. You can update via pip to test it, fix should be on conda later today.
