### ISSUE TITLE
Error during training when optimizing postprocessing

### ISSUE THREAD

**Issue by chitayata** [janclemenslab/das#46]
Dear Jan, 

I am trying to optimize postprocessing during training but I keep getting this error. 

`TypeError: train() got an unexpected keyword argument 'fill_gaps_min'`

I've tried in python and in the GUI with no luck. I know it can be a computationally intensive addition, but even with very small networks it doesn't work.  
Any idea what's going on?

Thanks!

**Comment by postpop** [comment]
Hi, I think that is a conda issue - can you post the output of `das version`? xarray-behave (the GUI) should be version 0.33.4. If this is not the case, updating xarray-behave through pip should help: `pip install xarray-behave --upgrade --no-deps`.

**Comment by chitayata** [comment]
Yup that was it. I had version 0.33.1. Updated now and seems to be running as normal.
thank you!
