### ISSUE TITLE
Make dataset for training error

### ISSUE THREAD

**Issue by emilierp** [janclemenslab/das#47]
Hello ! I am following the quickstart tutorial and whenever I try to "Make dataset for training" from the GUI, the log shows the following and nothing is created. 

`INFO:xarray_behave.gui.das:Collecting info on song types from annotation and definition files:
INFO:xarray_behave.gui.das:   /home/emilierp/Birds/quickstart/dmel_annotations.csv
INFO:xarray_behave.gui.das:Done.
INFO:xarray_behave.gui.das:   Identifying song types:
INFO:xarray_behave.gui.das:      Found pulse of type event
INFO:xarray_behave.gui.das:      Found sine of type segment
INFO:xarray_behave.gui.das:Done.
INFO:xarray_behave.gui.das:Collecting info on sample rates and channels from audio files:
Traceback (most recent call last):
  File "/home/emilierp/miniconda3/envs/das/lib/python3.9/site-packages/xarray_behave/gui/app.py", line 1892, in <lambda>
    menuitem.triggered.connect(lambda: callback(qt_keycode))
  File "/home/emilierp/miniconda3/envs/das/lib/python3.9/site-packages/xarray_behave/gui/app.py", line 417, in das_make
    das.make(data_folder=form_data['data_folder'],
  File "/home/emilierp/miniconda3/envs/das/lib/python3.9/site-packages/xarray_behave/gui/das.py", line 169, in make
    fss.add(fs)
TypeError: unhashable type: 'numpy.ndarray'
` 

Any help ? Thank you in advance !

**Comment by postpop** [comment]
Hi! Thanks for spotting this bug! Should be fixed now in v0.33.6 of the GUI xarray-behave. Conda packages will take 1-2 days to arrive but you can update via `pip install xarray-behave --upgrade --no-deps`.

**Comment by postpop** [comment]
yes, sorry - pushed another update of xarray-behave that should fix this. try via `pip install xarray-behave --upgrade --no-deps`.

**Comment by postpop** [comment]
Hi, I assume the latest upgrade fix this issue. Feel free to re-open if not.
