### ISSUE TITLE
Applicability of pretrained model

### ISSUE THREAD

**Issue by RubenTeunisse** [janclemenslab/das#48]
Hi!
I am using your pretrained model for mouse vocalizations on the parallel recordings of two sets of microphones.
Surprisingly, the model works great for one set of microphones, but not for the other.

For example, this is the spectrogram from mic set 1 (4 mics, 200kHz) with the output of the model in red:
![image](https://user-images.githubusercontent.com/32301392/194538981-9012299e-3922-42d2-ac04-e58a517474bd.png)
The vocalization probability clearly goes up at the start of the vocalization in the spectrogram.

For mic set 2 (64 mics, 250kHz), the model's output is almost always around 0.99, except for some edge effects and unreasonable band pass filters:
![image](https://user-images.githubusercontent.com/32301392/194539424-25628cc8-53f9-4152-972a-267bb81b69e8.png)
(Ignore the difference in shape of the images, both show roughly the same time window of 32ms and maximum frequency range)

The results are the same when I use a single mic from the set and when I use an average in frequency domain.
Furthermore, I am using the exact same function for resampling and reshaping the model input for the two mic sets.

Admittedly, the noise levels are slightly higher for mic set 2. Do you think this is what causes the difference?
Is there anything else I can try except for training a new model, or is that really the way to go?

Thanks!
Ruben

**Comment by postpop** [comment]
Hi Ruben, I don't think there is much you can do except train a new model. I don't think you will need a lot of manual annotations for that. And you'll have the added benefit of training a network that accepts the raw multi-channel data, which may be more robust to noise than a model trained on input merged across channels. I recommend you set the first TCN block to separable - so the "Separable TCN blocks" field for a model with two TCN blocks would be "True False". Happy to help more with the model design if you run into trouble.

**Comment by RubenTeunisse** [comment]
Okay, I will give that a try, thanks!
