### ISSUE TITLE
Error messages popping up during training and prediction after reinstalling DAS 

### ISSUE THREAD

**Issue by chitayata** [janclemenslab/das#49]
Hello Jan and team, 

I recently ran into some issues with the program that resulted in my removing and reinstalling anaconda on my computer. I reinstalled DAS and the GUI appears to be working normally except now I receive the below error message every time I train a network. The error message pops up at the very end of running the function. 

> INFO:das.train:   Saving to C:/Users/chita/OneDrive/Desktop/Chimp_vocalizations/Dataset_ChimpNetwork/Norm_PH_noise_FR200_2000hz.res/test_20221010_152304_results.h5.
> Traceback (most recent call last):
>   File "C:\Users\chita\miniconda3\envs\das\lib\site-packages\xarray_behave\gui\utils.py", line 222, in run
>     self.fn(*self.args, **self.kwargs)
>   File "C:\Users\chita\miniconda3\envs\das\lib\site-packages\das\train.py", line 486, in train
>     fl.save(save_filename, ddd)
>   File "C:\Users\chita\miniconda3\envs\das\lib\site-packages\flammkuchen\hdf5io.py", line 638, in save
>     _save_level(h5file, group, value, name=key,
>   File "C:\Users\chita\miniconda3\envs\das\lib\site-packages\flammkuchen\hdf5io.py", line 211, in _save_level
>     _save_level(handler, new_group, v, name=k, filters=filters,
>   File "C:\Users\chita\miniconda3\envs\das\lib\site-packages\flammkuchen\hdf5io.py", line 211, in _save_level
>     _save_level(handler, new_group, v, name=k, filters=filters,
>   File "C:\Users\chita\miniconda3\envs\das\lib\site-packages\flammkuchen\hdf5io.py", line 207, in _save_level
>     new_group = handler.create_group(group, name,
>   File "C:\Users\chita\miniconda3\envs\das\lib\site-packages\tables\file.py", line 908, in create_group
>     return Group(parentnode, name,
>   File "C:\Users\chita\miniconda3\envs\das\lib\site-packages\tables\group.py", line 221, in __init__
>     super().__init__(parentnode, name, _log)
>   File "C:\Users\chita\miniconda3\envs\das\lib\site-packages\tables\node.py", line 240, in __init__
>     parentnode._g_refnode(self, name, validate)
>   File "C:\Users\chita\miniconda3\envs\das\lib\site-packages\tables\group.py", line 492, in _g_refnode
>     check_name_validity(childname)
>   File "C:\Users\chita\miniconda3\envs\das\lib\site-packages\tables\path.py", line 144, in check_name_validity
>     raise ValueError("the ``/`` character is not allowed "
> ValueError: the ``/`` character is not allowed in object names: 'C:/Users/chita/OneDrive/Desktop/Chimp_vocalizations/Dataset_ChimpNetwork/Norm_PH_noise_FR200_2000hz\\PH_noise10'

I'm not really sure how and if this error is causing a problem though because the training does complete, giving me the training results and producing the usual 3 output files (results.h5, model.h5, and params.yaml). However,  I am also seeing other issues that perhaps all stem from the same problem. 

For instance, I also get an error while trying to predict on a new audio file:

> 
> ERROR:root:Error processing file C:/Users/chita/OneDrive/Desktop/Chimp_vocalizations/Dataset_ChimpNetwork/test\chimp_22.wav.
> Traceback (most recent call last):
>   File "C:\Users\chita\miniconda3\envs\das\lib\site-packages\das\predict.py", line 618, in cli_predict
>     events, segments, class_probabilities, class_names = predict(x,
>   File "C:\Users\chita\miniconda3\envs\das\lib\site-packages\das\predict.py", line 490, in predict
>     x = np.pad(x, ((0, pad_len), (0, 0)), mode='edge')
>   File "<__array_function__ internals>", line 180, in pad
>   File "C:\Users\chita\miniconda3\envs\das\lib\site-packages\numpy\lib\arraypad.py", line 793, in pad
>     padded, original_area_slice = _pad_simple(array, pad_width)
>   File "C:\Users\chita\miniconda3\envs\das\lib\site-packages\numpy\lib\arraypad.py", line 114, in _pad_simple
>     padded = np.empty(new_shape, dtype=array.dtype, order=order)
> numpy.core._exceptions._ArrayMemoryError: Unable to allocate 1.24 TiB for an array with shape (270336, 1261714) and data type float32

And now when I try to upload the model results into python, this code from the tutorial that used to work, gives me an error:

```
import flammkuchen as fl
import logging
logging.basicConfig(level=logging.INFO)
res_name = 'Norm_PH_noise_FR200_2000hz.res/Final_8192_bat16_lr002reduce_20221007_134838'
res = fl.load(f'{res_name}_results.h5')
```

> KeyError                                  Traceback (most recent call last)
> File ~\miniconda3\envs\das\lib\site-packages\flammkuchen\hdf5io.py:479, in _load_level(handler, level, pathtable)
>     478 try:
> --> 479     return pathtable[pathname]
>     480 except KeyError:
> 
> KeyError: '/'
> 
> During handling of the above exception, another exception occurred:
> 
> KeyError                                  Traceback (most recent call last)
> File ~\miniconda3\envs\das\lib\site-packages\flammkuchen\hdf5io.py:479, in _load_level(handler, level, pathtable)
>     478 try:
> --> 479     return pathtable[pathname]
>     480 except KeyError:
> 
> KeyError: '/y_pred'
> 
> During handling of the above exception, another exception occurred:
> 
> KeyError                                  Traceback (most recent call last)
> File ~\miniconda3\envs\das\lib\site-packages\zarr\core.py:241, in Array._load_metadata_nosync(self)
>     240     mkey = _prefix_to_array_key(self._store, self._key_prefix)
> --> 241     meta_bytes = self._store[mkey]
>     242 except KeyError:
> 
> File ~\miniconda3\envs\das\lib\site-packages\zarr\storage.py:1074, in DirectoryStore.__getitem__(self, key)
>    1073 else:
> -> 1074     raise KeyError(key)
> 
> KeyError: '.zarray'
> 
> During handling of the above exception, another exception occurred:
> 
> ArrayNotFoundError                        Traceback (most recent call last)
> Cell In [5], line 6
>       4 logging.basicConfig(level=logging.INFO)
>       5 res_name = 'Norm_PH_noise_FR200_2000hz.res/Final_8192_bat16_lr002reduce_20221007_134838'
> ----> 6 res = fl.load(f'{res_name}_results.h5')
>       7 res
> 
> File ~\miniconda3\envs\das\lib\site-packages\flammkuchen\hdf5io.py:718, in load(path, group, sel, unpack)
>     715     raise ValueError("Must specify group with `sel` unless it "
>     716                      "automatically unpacks")
>     717 else:
> --> 718     data = _load_level(h5file, grp, pathtable)
>     720 if DEEPDISH_IO_VERSION_STR in grp._v_attrs:
>     721     v = grp._v_attrs[DEEPDISH_IO_VERSION_STR]
> 
> File ~\miniconda3\envs\das\lib\site-packages\flammkuchen\hdf5io.py:481, in _load_level(handler, level, pathtable)
>     479     return pathtable[pathname]
>     480 except KeyError:
> --> 481     pathtable[pathname] = _load_nonlink_level(handler, node, pathtable,
>     482                                               pathname)
>     483     return pathtable[pathname]
> 
> File ~\miniconda3\envs\das\lib\site-packages\flammkuchen\hdf5io.py:370, in _load_nonlink_level(handler, level, pathtable, pathname)
>     368 # Load sub-groups
>     369 for grp in level:
> --> 370     lev = _load_level(handler, grp, pathtable)
>     371     n = grp._v_name
>     372     # Check if it's a complicated pair or a string-value pair
> 
> File ~\miniconda3\envs\das\lib\site-packages\flammkuchen\hdf5io.py:481, in _load_level(handler, level, pathtable)
>     479     return pathtable[pathname]
>     480 except KeyError:
> --> 481     pathtable[pathname] = _load_nonlink_level(handler, node, pathtable,
>     482                                               pathname)
>     483     return pathtable[pathname]
> 
> File ~\miniconda3\envs\das\lib\site-packages\flammkuchen\hdf5io.py:437, in _load_nonlink_level(handler, level, pathtable, pathname)
>     435 elif isinstance(level, tables.VLArray):
>     436     if level.shape == (1,):
> --> 437         return _load_pickled(level)
>     438     else:
>     439         return level[:]
> 
> File ~\miniconda3\envs\das\lib\site-packages\flammkuchen\hdf5io.py:343, in _load_pickled(level)
>     342 def _load_pickled(level):
> --> 343     if isinstance(level[0], ForcePickle):
>     344         return level[0].obj
>     345     else:
> 
> File ~\miniconda3\envs\das\lib\site-packages\tables\vlarray.py:662, in VLArray.__getitem__(self, key)
>     660         key += self.nrows
>     661     (start, stop, step) = self._process_range(key, key + 1, 1)
> --> 662     return self.read(start, stop, step)[0]
>     663 elif isinstance(key, slice):
>     664     start, stop, step = self._process_range(
>     665         key.start, key.stop, key.step)
> 
> File ~\miniconda3\envs\das\lib\site-packages\tables\vlarray.py:806, in VLArray.read(self, start, stop, step)
>     804 atom = self.atom
>     805 if not hasattr(atom, 'size'):  # it is a pseudo-atom
> --> 806     outlistarr = [atom.fromarray(arr) for arr in listarr]
>     807 else:
>     808     # Convert the list to the right flavor
>     809     flavor = self.flavor
> 
> File ~\miniconda3\envs\das\lib\site-packages\tables\vlarray.py:806, in <listcomp>(.0)
>     804 atom = self.atom
>     805 if not hasattr(atom, 'size'):  # it is a pseudo-atom
> --> 806     outlistarr = [atom.fromarray(arr) for arr in listarr]
>     807 else:
>     808     # Convert the list to the right flavor
>     809     flavor = self.flavor
> 
> File ~\miniconda3\envs\das\lib\site-packages\tables\atom.py:1175, in ObjectAtom.fromarray(self, array)
>    1173 if array.size == 0:
>    1174     return None
> -> 1175 return pickle.loads(array.tobytes())
> 
> File ~\miniconda3\envs\das\lib\site-packages\zarr\core.py:2405, in Array.__setstate__(self, state)
>    2404 def __setstate__(self, state):
> -> 2405     self.__init__(**state)
> 
> File ~\miniconda3\envs\das\lib\site-packages\zarr\core.py:215, in Array.__init__(self, store, path, read_only, chunk_store, synchronizer, cache_metadata, cache_attrs, partial_decompress, write_empty_chunks, zarr_version, meta_array)
>     212     self._metadata_key_suffix = self._hierarchy_metadata['metadata_key_suffix']
>     214 # initialize metadata
> --> 215 self._load_metadata()
>     217 # initialize attributes
>     218 akey = _prefix_to_attrs_key(self._store, self._key_prefix)
> 
> File ~\miniconda3\envs\das\lib\site-packages\zarr\core.py:232, in Array._load_metadata(self)
>     230 """(Re)load metadata from store."""
>     231 if self._synchronizer is None:
> --> 232     self._load_metadata_nosync()
>     233 else:
>     234     mkey = _prefix_to_array_key(self._store, self._key_prefix)
> 
> File ~\miniconda3\envs\das\lib\site-packages\zarr\core.py:243, in Array._load_metadata_nosync(self)
>     241     meta_bytes = self._store[mkey]
>     242 except KeyError:
> --> 243     raise ArrayNotFoundError(self._path)
>     244 else:
>     245 
>     246     # decode and store metadata as instance members
>     247     meta = self._store._metadata_class.decode_array_metadata(meta_bytes)
> 
> ArrayNotFoundError: array not found at path %r' ''

I'm totally lost on what the issue is. Any thoughts on what could be causing all these errors? I'm not sure if this is related to my needing to delete and reinstall python. I followed the tutorial same as before, but perhaps DAS didn't install correctly? 
Any advice is appreciated. 

Many thanks!

**Comment by postpop** [comment]
Ugh, looks like something went terribly wrong - I'll look into it asap.

**Comment by postpop** [comment]
Can you print the output of `das version` and also the output of the following command? Thanks.
`python -c 'import flammkuchen;print(flammkuchen.__version__)'` (will print the version of flammkuchen which seems to throw most of these errors)

**Comment by chitayata** [comment]
Thanks for getting back so quickly. 
2nd line doesn't seem to be working

> > (das) C:\Users\chita>das version
> INFO:das.cli:  Windows-10-10.0.22621-SP0
> INFO:das.cli:  DAS v0.28.2
> INFO:das.cli:     GUI is available.
> INFO:das.cli:     xarray-behave v0.33.5
> INFO:das.cli:     pyqtgraph v0.13.1
> INFO:das.cli:     PySide2 v5.13.2
> INFO:das.cli:     Qt v5.12.9
> INFO:das.cli:
> INFO:das.cli:  tensorflow v2.6.0
> INFO:das.cli:  keras v2.6.0
> INFO:das.cli:     GPU is  available.
> INFO:das.cli:
> INFO:das.cli:  python v3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:50:36) [MSC v.1929 64 bit (AMD64)]
> INFO:das.cli:  pandas v1.5.0
> INFO:das.cli:  numpy v1.23.3
> INFO:das.cli:  h5py v3.7.0
> INFO:das.cli:  scipy v1.9.1
> INFO:das.cli:  scikit-learn v1.1.2
> INFO:das.cli:  xarray v2022.9.0

This code doesn't seem to be working
> (das) C:\Users\chita>python -c 'import flammkuchen; print(flammkuchen.__version__)'
>   File "<string>", line 1
>     'import
>            ^
> SyntaxError: EOL while scanning string literal

But this gives what you want I think
> (das) C:\Users\chita>conda list flammkuchen
> packages in environment at C:\Users\chita\miniconda3\envs\das:
> 
>  Name                    Version                   Build  Channel
> flammkuchen               0.9.2                      py_0    conda-forge

**Comment by chitayata** [comment]
great news thank you!

**Comment by postpop** [comment]
New v0.28.3 should fix all these issues - you can update now via pip: `pip install das --upgrade --no-deps`. Will take a bit for it to appear on conda. Feel free to re-open if the issues persist after the upgrade.
