### ISSUE TITLE
multple predictions for the same vocalization

### ISSUE THREAD

**Issue by ralphpeterson** [janclemenslab/das#56]
Hi Jan, 

Have you ever seen multiple predictions for the same vocalization like below? This is my first time predicting on this file — the model was trained (and looks good) on a different file.

<img width="327" alt="image" src="https://user-images.githubusercontent.com/4031329/201782334-87fe1be9-76f0-4bc2-9e75-03309081ed93.png">

Best,
Ralph

**Comment by postpop** [comment]
Yes, that looks familiar - I bet that if you zoom in, these are many, very short "syllables" with very short gaps in between them. In the prediction dialog, there are two options two fix that:
- _Fill gaps shorter than (__seconds__)_ will merge detections with short gaps in between them
- _Delete segments shorter than (__seconds__)_ will delete remaining detections that are very short.

You can optimize these parameters during training, via the "Optimize postprocessing" part of the training dialog. In your case, it's probably easier to set these manually based on the statistics of the vocalizations in your data or based on the annotation errors you'd like to fix. I guess calls in your data are always separated by more than 10ms and are always longer than 10ms. Setting the above parameters to 10ms (0.01 seconds) should fix the issue in your case.

**Comment by ralphpeterson** [comment]
That worked great, thanks!
