### ISSUE TITLE
Locating annotations in a large data folder

### ISSUE THREAD

**Issue by chitayata** [janclemenslab/das#59]
Dear Jan,

Is there a way to apply the DAS model to a large dataset but filter results so that I am able to locate the files where predictions/annotations have been made (versus files where my vocalization was not detected)? 

My dataset contains 1000s of individual acoustic files that were collected on a daily basis via passive acoustic monitoring, thus I expect only a relatively small percentage of these files contain my vocalization of interest.
However, after applying the model to the folder, results are in separate files that correspond to my original acoustic files, requiring me to open each file in order to see if 1) a vocalization was precited, 2) it is accurate.  

Any suggestions for how to work around this would be greatly appreciated.
Thank you!

**Comment by postpop** [comment]
Hi,

one way of dealing with this would be to load all the annotation files and print a list of recordings with detections. That way you can focus on only loading files with detections. Note that with this, you won't be able to detect false positives but not false negatives - calls that DAS did not detect. 

Alternatively, you could merge/concatenate multiple recordings and their annotations into only a handful of files. That way, you only have to open a few files and can inspect them quickly. 

I'm happy to help with that - feel free to contact me via  email.
