### ISSUE TITLE
Left clicks in GUI doesn't create annotations

### ISSUE THREAD

**Issue by WalidERRAIS** [janclemenslab/das#61]
Hi, I'm on ubuntu 20.04 and I have das 0.30.0 install. I took your example audio file Dmel_male.wav, I loaded the audio with the GUI but when I tried to annotate manually it doesn't work. 

I created the songs types pulse and sine, then I choosed the song type but left clicking in waveform or spectrogram doesn't create annotations. It create annotations just with the Thresholding mode.

**Comment by WalidERRAIS** [comment]
Hi, thanks for your quick response, it works.

**Comment by Pia-gdt** [comment]
Hi, I have the same issue with version 0.32.4. Any idea what could cause it?

 Here are the version information:
```
INFO:das.cli:  Windows-10-10.0.19045-SP0
INFO:das.cli:  DAS v0.32.4
INFO:das.cli:     GUI is available.
INFO:das.cli:     xarray-behave v0.35.7
INFO:das.cli:     pyqtgraph v0.13.7
INFO:das.cli:     PySide6 v6.8.1
INFO:das.cli:     Qt v6.8.1
INFO:das.cli:
INFO:das.cli:  tensorflow v2.10.1
INFO:das.cli:  keras v2.10.0
INFO:das.cli:     GPU is  available.
INFO:das.cli:
INFO:das.cli:  python v3.10.16 | packaged by conda-forge | (main, Dec  5 2024, 14:07:43) [MSC v.1942 64 bit (AMD64)]
INFO:das.cli:  pandas v2.2.3
INFO:das.cli:  numpy v1.26.4
INFO:das.cli:  h5py v3.12.1
INFO:das.cli:  scipy v1.15.0
INFO:das.cli:  scikit-learn v1.6.0
INFO:das.cli:  xarray v2025.1.0
```

**Comment by postpop** [comment]
Hi, thanks for reporting this issue. Should be fixed with the next build, which should be live tomorrow. 
Please reinstall tomorrow and let me know if this does indeed solve your problem.

**Comment by Pia-gdt** [comment]
Hi, it works! Thanks
