### ISSUE TITLE
fix y axis in waveform GUI problem

### ISSUE THREAD

**Issue by WalidERRAIS** [janclemenslab/das#62]
Hi,

During annotation with the GUI, I try to set the scale of the waveform y axis but when I move the y axis scale changes with the maximum amplitude. I would like to fix the y-axis scale on the GUI when I move.

I try to change manually the min and max on the axis y but the configuration does not remain saved.

**Comment by postpop** [comment]
Hi,

you can set the vertical limits for the waveform view in the Menu "View/Video...display parameters".

**Comment by WalidERRAIS** [comment]
Hi,

Thank you it works for me.
