### ISSUE TITLE
Installation on arm Macs (M1 Macbook Air)

### ISSUE THREAD

**Issue by postpop** [janclemenslab/das#65]
I've got similar issues during installation on Mac (M1 Macbook Air).

Code executed:
`mamba create python=3.9 das=0.31.0 -c conda-forge -c ncb -c anaconda -c nvidia -n das -y`

Result:
```
Could not solve for environment specs
The following package could not be installed
└─ das 0.31.0**  is not installable because it requires
   └─ tensorflow-deps 2.9.* , which does not exist (perhaps a missing channel).
```

I also tried to install tensorflow-deps 2.9.0 independently from the apple channel. 
`mamba install tensorflow-deps=2.9.0 -c apple`

However, this raises a much longer dependency-conflict list.
Should I install tensorflow-deps in different ways?

_Originally posted by @kaede-kmr in https://github.com/janclemenslab/das/issues/63#issuecomment-1860498183_

**Comment by postpop** [comment]
Hi, thanks for raising the issue, DAS does work on arm64 Macs, but installation is not as robust as we want it to be atm.
We are working on that and I will let you know once the issue is solved.

For now, this line resulted in a working DAS installation on my M1 mac:
```shell
mamba create python=3.9 das=0.31.0 pyside2 defopt=6.3 -c conda-forge -c ncb -c anaconda -c nvidia -c apple -n das -y```

**Comment by postpop** [comment]
Hi, we've updated the conda package. Installing with this line should now work on all systems:
```
mamba create -n dasx -c conda-forge -c ncb -c apple -c anaconda das=0.31.0 python=3.9
```

Could you test this and let me know if it works for you, too? We'll update the docs accordingly.

**Comment by kaede-kmr** [comment]
Thank you very much!
Yes, the above line allowed me to install DAS and open up the gui for both M1 Macbook Air and my old Intel iMac.
I will play around with it for my frog call recordings.

**Comment by postpop** [comment]
Great - happy to hear that it works now! Let me know if you need advice on using DAS for analyzing your frog data.
