### ISSUE TITLE
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in "/home/ejhc/.local/lib/python3.10/site-packages/cv2/qt/plugins"

### ISSUE THREAD

**Issue by ecsendmail** [janclemenslab/das#69]
There are two plugins that fail the "das gui" command:
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in "/home/ejhc/.local/lib/python3.10/site-packages/cv2/qt/plugins" AND
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in "/home/ejhc/.local/lib/python3.10/site-packages/cv2/qt/plugins"

My environment is Windows 11 on ASUS Vivobook running Intel i9 and Intel IRIS graphics with 16GB RAM and 1TB storage, using the latest edition of WSL and newly installed from github janclemenslab directions of miniconda3 and the mamba installations of:

conda install mamba -c conda-forge -n base -y
mamba create python=3.10 das=0.32.1 -c conda-forge -c ncb -c anaconda -c nvidia -c apple -n das -y

I have tried to find simple ways to deal with the missing plugin's wayland and xcb and discovered that I may have to do down the rabbit hole of compiling plugins in C++ and installing them somehow....

Can you help me find an easier way like pip get-apt something to put these two plugins where they need to be wherever das gui calls them from? Or a new install of qt.gpa.plugin?

Thanks
Ernie Chang

**Comment by ecsendmail** [comment]
Further to the above, it appears that all the Qt library is out of synd:

qt.core.plugin.loader: In /home/ejhc/miniconda3/envs/das/plugins/platforms/libqeglfs.so:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In /home/ejhc/miniconda3/envs/das/plugins/platforms/libqvnc.so:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In /home/ejhc/miniconda3/envs/das/plugins/platforms/libqminimal.so:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In /home/ejhc/miniconda3/envs/das/plugins/platforms/libqoffscreen.so:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In /home/ejhc/miniconda3/envs/das/plugins/platforms/libqxcb.so:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In /home/ejhc/miniconda3/envs/das/plugins/platforms/libqminimalegl.so:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In /home/ejhc/miniconda3/envs/das/plugins/platforms/libqwebgl.so:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in "/home/ejhc/.local/lib/python3.10/site-packages/cv2/qt/plugins"
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in "/home/ejhc/.local/lib/python3.10/site-packages/cv2/qt/plugins"
T

Please help me with how I might get this up to date. I note that Qt itself is a commercial enterprise and the latest edition of the "Qt framework" is 6.6.0 whereas the error messages refer to 5.15.0.....

Thank you
Ernie Chang

**Comment by postpop** [comment]
Hi, thanks for raising this issue. Generally, GUI support on WSL is still a bit shaky. In DAS, training and inference from the command line using `das train` and `das predict` do work. But the GUI does not. If you want to use the GUI, I recommend you install DAS not in a WSL terminal but via a regular windows shell.
