### ISSUE TITLE
installation error with updated das name

### ISSUE THREAD

**Issue by xingjeffrey** [janclemenslab/das#8]
I just tried to install das with `conda env create -f https://raw.githubusercontent.com/janclemenslab/das/master/env/das_gui.yml -n das`, and a Pip subprocess error pops out which prevents das from installing properly. The following is the exact message:

`Pip subprocess error:
ERROR: Could not find a version that satisfies the requirement das-unsupervised (from versions: none)
ERROR: No matching distribution found for das-unsupervised

failed

CondaEnvException: Pip failed`

I tried doing `pip install das-unsupervised` by itself, but it was also not working and gives the same error. 

Seeing that the name change for the package just happened few hours ago, you are probably already aware of this issue, but just in case.

**Comment by postpop** [comment]
Hi Jeffrey,

thanks for the note. You are right - I was in the process of re-naming the package and there were still some bugs to be fixed. Should be working again.
