### ISSUE TITLE
GUI cannot File/Export for DAS

### ISSUE THREAD

**Issue by xingjeffrey** [janclemenslab/das#9]
When attempting to export manual annotations for training via File/Export for DAS, the consequent dialog box does not pop up, and instead the following error is displayed on the console:

`Traceback (most recent call last):
  File "c:\users\jeffr\anaconda3\envs\das\lib\site-packages\xarray_behave\gui\app.py", line 1367, in <lambda>
    menuitem.triggered.connect(lambda: callback(qt_keycode))
  File "c:\users\jeffr\anaconda3\envs\das\lib\site-packages\xarray_behave\gui\app.py", line 284, in export_for_das
    with open(yaml_file, "r") as form_yaml:
FileNotFoundError: [Errno 2] No such file or directory: 'c:\\users\\jeffr\\anaconda3\\envs\\das\\lib\\site-packages\\xarray_behave/gui/forms/export_for_das.yaml'`

This is probably also due to the rename and you are probably working on it, but again, just in case.

**Comment by postpop** [comment]
Terribly sorry about the mess and thanks for your patience and your bug reports!
I've fixed the issue in the latest version of the gui.
`pip install xarray-behave --upgrade` should to the trick.
